%%% This file was automatically generated by snmpc_mib_to_hrl version 4.22.1
%%% Date: 03-Sep-2012::12:08:04
-ifndef('OTP-TC').
-define('OTP-TC', true).

%% Oids

-define(otpTcModule, [1,3,6,1,4,1,193,19,1,1,2]).


%% Range values


%% Default values

-endif.
